<?php
namespace Shared\Libraries\Jaeger\Thrift;
/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


interface DependencyIf {
  /**
   * @param string $traceId
   * @return \Shared\Libraries\Jaeger\Thrift\Dependencies
   */
  public function getDependenciesForTrace($traceId);
  /**
   * @param \Shared\Libraries\Jaeger\Thrift\Dependencies $dependencies
   */
  public function saveDependencies(\Shared\Libraries\Jaeger\Thrift\Dependencies $dependencies);
}


